name = "oldnews-backend"
main = "src/index.js"
compatibility_date = "2024-02-08"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "old_news"
database_id = "033629f6-6004-44ff-a924-846e67f12cdb"

